/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "Button_1.h"
#include "Button_1_aliases.h"
#include "LED_2.h"
#include "LED_2_aliases.h"
#include "Button_2.h"
#include "Button_2_aliases.h"
#include "LED_3.h"
#include "LED_3_aliases.h"
#include "Button_3.h"
#include "Button_3_aliases.h"
#include "LED_4.h"
#include "LED_4_aliases.h"
#include "Button_4.h"
#include "Button_4_aliases.h"
#include "Reset.h"
#include "Reset_aliases.h"
#include "Buzzer_1.h"
#include "Buzzer_1_aliases.h"
#include "Buzzer_2.h"
#include "Buzzer_2_aliases.h"
#include "LCD_Char_1.h"
#include "LCD_Char_1_LCDPort.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

